Heima8.OA.UI.Portal/Controllers/ActionInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Heima8.OA.IBLL;
using Heima8.OA.Model;

namespace Heima8.OA.UI.Portal.Controllers
{
    public class ActionInfoController : BaseController
    {
        short delflagNormal = (short)Heima8.OA.Model.Enum.DelFlagEnum.Normal;
        //
        // GET: /ActionInfo/

        public IActionInfoService ActionInfoService { get; set; }
        public IUserInfoService UserInfoService { get; set; }
        public IRoleInfoService RoleInfoService { get; set; }
        public ActionResult Index()
        {
            return View();
        }

        #region 加载数据
        public ActionResult GetAllActionInfos()
        {
            //easyui: table在初始化时候自动发送以下两个参数值。
            int pageSize = int.Parse(Request["rows"] ?? "10");
            int pageIndex = int.Parse(Request["page"] ?? "1");
            int total = 0;

            var temp = ActionInfoService.GetPageEntities(pageSize, pageIndex, out total,
                                              u => u.DelFlag == delflagNormal, u => u.ID, true);

            var tempData =
                temp.Select(
                    a =>
                    new
                        {
                            a.ID,
                            a.IsMenu,
                            a.Url,
                            a.Remark,
                            a.Sort,
                            a.SubTime,
                            a.ModfiedOn,
                            a.HttpMethd,
                            a.MenuIcon,
                            a.ActionName
                        });

            var data = new { total = total, rows = tempData.ToList() };
            return Json(data, JsonRequestBehavior.AllowGet);
        } 
        #endregion

        #region Add

        public ActionResult Add(ActionInfo actionInfo)
        {
            actionInfo.ModfiedOn = DateTime.Now;
            actionInfo.SubTime = DateTime.Now;
            actionInfo.DelFlag = delflagNormal;

            actionInfo.IsMenu = Request["IsMenu"] == "true" ? true : false;

            ActionInfoService.Add(actionInfo);
            return Content("ok");
        }

        #endregion

        #region 删除
        public ActionResult Delete(string ids)
        {
            if (string.IsNullOrEmpty(ids))
            {
                return Content("请选中要删除数据！");
            }

            //正常处理
            string[] strIds = ids.Split(',');
            List<int> idList = new List<int>();
            foreach (var strId in strIds)
            {
                idList.Add(int.Parse(strId));
            }
            //UserInfoService.DeleteList(idList);
            ActionInfoService.DeleteListByLogical(idList);
            return Content("ok");

        }
        #endregion

        #region 修改
        public ActionResult Edit(int id)
        {
            ViewData.Model = ActionInfoService.GetEntities(u => u.ID == id).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public ActionResult Edit(ActionInfo userInfo)
        {
            ActionInfoService.Update(userInfo);
            return Content("ok");
        }
        #endregion

        #region 上传图片处理
        public ActionResult UploadImage()
        {
            var file= Request.Files["fileMenuIcon"];

            string path = "/UploadFiles/UploadImgs/"+Guid.NewGuid().ToString()+"-"+file.FileName;
            
            file.SaveAs(Request.MapPath(path));
            

            return Content(path);
        }
        #endregion

        #region 设置角色
        public ActionResult SetRole(int id)
        {
            //当前要设置角色的用户
            int userId = id;

            ActionInfo actionInfo = ActionInfoService.GetEntities(u => u.ID == id).FirstOrDefault();

            //把所有的角色发送 到前台
            ViewBag.AllRoles = RoleInfoService.GetEntities(u => u.DelFlag == delflagNormal).ToList();

            //用户已经关联的角色发送到前台。
            ViewBag.ExitsRoles = (from r in actionInfo.RoleInfo
                                  select r.ID).ToList();

            return View(actionInfo);

        }

        //给用户设置角色
        public ActionResult ProcessSetRole(int UId)
        {
            //第一：当前用户id  --uid
            //第二：所有打上对勾的 角色。 ---> list
            List<int> setRoleIdList = new List<int>();
            foreach (var key in Request.Form.AllKeys)
            {
                if (key.StartsWith("ckb_"))
                {
                    int roleId = int.Parse(key.Replace("ckb_", ""));
                    setRoleIdList.Add(roleId);
                }
            }

            ActionInfoService.SetRole(UId, setRoleIdList);
            return Content("ok");

        }

        #endregion
    }
}

Heima8.OA.UI.Portal/Views/ActionInfo/Edit.cshtml
@model Heima8.OA.Model.ActionInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
     <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function afterEdit(data) {
            if (data == "ok") {
                window.parent.window.afterEditSuccess();
            } else {
                alert("败了");
            }
        }

        function submitForm() {
            $("form").submit();
        }
    </script>
</head>
<body>
    
    
    @using (Ajax.BeginForm(new AjaxOptions() { OnSuccess = "afterEdit" }))
    {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>修改权限</legend>
    
            @Html.HiddenFor(model => model.ID)
       @Html.HiddenFor(model => model.SubTime)
             @Html.HiddenFor(model => model.ModfiedOn)
       @Html.HiddenFor(model => model.DelFlag)
          
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Remark)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Remark)
                @Html.ValidationMessageFor(model => model.Remark)
            </div>
    
         
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.HttpMethd)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.HttpMethd)
                @Html.ValidationMessageFor(model => model.HttpMethd)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ActionName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ActionName)
                @Html.ValidationMessageFor(model => model.ActionName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.IsMenu)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsMenu)
                @Html.ValidationMessageFor(model => model.IsMenu)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.MenuIcon)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MenuIcon)
                @Html.ValidationMessageFor(model => model.MenuIcon)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Sort)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Sort)
                @Html.ValidationMessageFor(model => model.Sort)
            </div>
    
            <p>
                <input type="submit" value="保存" />
            </p>
        </fieldset>
    }
    
 
</body>
</html>

Heima8.OA.UI.Portal/Views/ActionInfo/SetRole.cshtml
@using Heima8.OA.Model
@model Heima8.OA.Model.ActionInfo

@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function afterSetRole(data) {
            if (data == "ok") {
                window.parent.window.afterSetRole();
            }
        }

        function submitForm() {
            $("form").submit();
        }
    </script>
</head>
<body>
    <div>
        <h2>当前给权限：  @Model.ActionName 设置角色</h2>
        <hr />
        @{
            //所有的角色
            List<RoleInfo> allRoles = ViewBag.AllRoles;
            //所有当前用户已经存在的角色
            List<int> existRoleIdList = ViewBag.ExitsRoles;
            
            using (Ajax.BeginForm("ProcessSetRole", "ActionInfo", new AjaxOptions() { OnSuccess = "afterSetRole" }))
            {

            <input type="hidden" name="UId" value="@Model.ID"/>
                
                int i = 0;
                foreach (var roleInfo in allRoles)
                {
                    string str = "ckb_" + roleInfo.ID;
                    if (i % 3 == 0 && i != 0)
                    {
                        <hr />
                    }
                    if (existRoleIdList.Contains(roleInfo.ID))
                    {
                        <input type="checkbox" checked="checked" value="@str" name="@str" id="@str"/>
                    }
                    else
                    {
                        <input type="checkbox"  value="@str" name="@str" id="@str"/>
                    }
                    
                    <label for="@str">@roleInfo.RoleName</label>

                    i++;

                }
            }
        }
    </div>
</body>
</html>