Heima8.OA.UI.Portal/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Heima8.OA.BLL;
using Heima8.OA.IBLL;
using Heima8.OA.Model;
using Heima8.OA.Model.Param;

namespace Heima8.OA.UI.Portal.Controllers
{
    public class UserInfoController : BaseController
    {
        short delflagNormal = (short)Heima8.OA.Model.Enum.DelFlagEnum.Normal;
        //
        // GET: /UserInfo/
        //UserInfoService UserInfoService =new UserInfoService();//Spring.Net
        public IUserInfoService UserInfoService { get; set; }
        public IRoleInfoService RoleInfoService { get; set; }
        public IR_UserInfo_ActionInfoService R_UserInfo_ActionInfoService { get; set; }
        public IActionInfoService ActionInfoService { get; set; }

        #region 获取用户

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GetAllUserInfos()
        {
            //jquery easyui: table: {total:32,rows:[{},{}]}

            //easyui: table在初始化时候自动发送以下两个参数值。
            int pageSize = int.Parse(Request["rows"] ?? "10");
            int pageIndex = int.Parse(Request["page"] ?? "1");
            int total = 0;

            //过滤的用户名   过滤备注schName   schRemark
            string schName = Request["schName"];
            string schRemark = Request["schRemark"];

            

            var queryParam= new UserQueryParam()
                {
                    PageIndex = pageIndex,
                    PageSize = pageSize,
                    Total = 0,
                    SchName = schName,
                    SchRemark = schRemark
                };

            var pageData = UserInfoService.LoagPageData(queryParam);

            var temp = pageData.Select(u => new
            {
                ID = u.ID,
                u.UName,
                u.Remark,
                u.ShowName,
                u.SubTime,
                u.ModfiedOn,
                u.Pwd
            });


            //拿到当前页的数据
            //var pageData = UserInfoService.GetPageEntities(pageSize, pageIndex, out total,
            //                                                u => u.DelFlag == delflagNormal, u => u.ID, true)
            //.select(
            //      u =>
            //      new
            //      {
            //          id = u.id,
            //          u.uname,
            //          u.remark,
            //          u.showname,
            //          u.subtime,
            //          u.modfiedon,
            //          u.pwd
            //      });


            var data = new { total = queryParam.Total, rows = temp.ToList() };

            return Json(data, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 添加用户
        public ActionResult Add(UserInfo userInfo)
        {
            userInfo.ModfiedOn = DateTime.Now;
            userInfo.SubTime = DateTime.Now;
            userInfo.DelFlag = (short)Heima8.OA.Model.Enum.DelFlagEnum.Normal;

            UserInfoService.Add(userInfo);

            return Content("ok");
        }
        #endregion


        #region 修改
        public ActionResult Edit(int id)
        {
            ViewData.Model = UserInfoService.GetEntities(u => u.ID == id).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public ActionResult Edit(UserInfo userInfo)
        {
            UserInfoService.Update(userInfo);
            return Content("ok");
        }
        #endregion

        #region 删除
        public ActionResult Delete(string ids)
        {
            if (string.IsNullOrEmpty(ids))
            {
                return Content("请选中要删除数据！");
            }

            //正常处理
            string[] strIds = ids.Split(',');
            List<int> idList = new List<int>();
            foreach (var strId in strIds)
            {
                idList.Add(int.Parse(strId));
            }
            //UserInfoService.DeleteList(idList);
            UserInfoService.DeleteListByLogical(idList);
            return Content("ok");

        }
        #endregion


        #region create

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                UserInfoService.Add(userInfo);
            }
            return RedirectToAction("Index");
        }
        #endregion


        #region 设置角色
        public ActionResult SetRole(int id)
        {
            //当前要设置角色的用户
            int userId = id;
            
            UserInfo  user= UserInfoService.GetEntities(u => u.ID == id).FirstOrDefault();

            //把所有的角色发送 到前台
            ViewBag.AllRoles = RoleInfoService.GetEntities(u => u.DelFlag == delflagNormal).ToList();

            //用户已经关联的角色发送到前台。
            ViewBag.ExitsRoles = (from r in user.RoleInfo
                                  select r.ID).ToList();

            return View(user);

        }

        //给用户设置角色
        public ActionResult ProcessSetRole(int UId)
        {
            //第一：当前用户id  --uid
            //第二：所有打上对勾的 角色。 ---> list
            List<int> setRoleIdList =new List<int>();
            foreach (var key in Request.Form.AllKeys)
            {
                if (key.StartsWith("ckb_"))
                {
                    int roleId = int.Parse(key.Replace("ckb_", ""));
                    setRoleIdList.Add(roleId);
                }
            }

            UserInfoService.SetRole(UId, setRoleIdList);
            return Content("ok");

        }

        #endregion

        #region 设置特殊权限
        public ActionResult SetAction(int id)
        {
            ViewBag.User = UserInfoService.GetEntities(u => u.ID == id).FirstOrDefault();

            ViewData.Model = ActionInfoService.GetEntities(a => a.DelFlag == delflagNormal).ToList();

            return View();
        }

        //做一个删除  特殊权限。
        public ActionResult DeleteUserAction(int UId, int ActionId)
        {

            var rUserAction= R_UserInfo_ActionInfoService.GetEntities(r => r.ActionInfoID == ActionId && r.UserInfoID == UId)
                                        .FirstOrDefault();
            if (rUserAction != null)
            {
                //rUserAction.DelFlag = (short) Heima8.OA.Model.Enum.DelFlagEnum.Deleted;
                R_UserInfo_ActionInfoService.DeleteListByLogical(new List<int>() {rUserAction.ID});
            }
            return Content("ok");
        }


        //设置当前用户的特殊权限
        public ActionResult SetUserAction(int UId, int ActionId, int Value)
        {
            //{UId:uId,ActionId:actionId,Value:value}
              var rUserAction= R_UserInfo_ActionInfoService.GetEntities(r => r.ActionInfoID == ActionId && r.UserInfoID == UId && r.DelFlag==delflagNormal)
                                        .FirstOrDefault();
            if (rUserAction != null)
            {
                rUserAction.HasPermission = Value == 1 ? true : false;
                R_UserInfo_ActionInfoService.Update(rUserAction);
            }
            else
            {
                R_UserInfo_ActionInfo rUserInfoActionInfo =new R_UserInfo_ActionInfo();
                rUserInfoActionInfo.ActionInfoID = ActionId;
                rUserInfoActionInfo.UserInfoID = UId;
                rUserInfoActionInfo.HasPermission = Value == 1 ? true : false;
                rUserInfoActionInfo.DelFlag = delflagNormal;
                R_UserInfo_ActionInfoService.Add(rUserInfoActionInfo);
            }

            return Content("ok");
        }

        #endregion
    }
}

Heima8.OA.UI.Portal/Views/UserInfo/Create.cshtml
@model Heima8.OA.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>UserInfo</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.UName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.UName)
                @Html.ValidationMessageFor(model => model.UName)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Heima8.OA.UI.Portal/Views/UserInfo/Edit.cshtml
@model Heima8.OA.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function afterEdit(data) {
              if (data == "ok") {
                  window.parent.window.afterEditSuccess();
              } else {
                  alert("败了");
              }
        }

        function submitForm() {
            $("form").submit();
        }
    </script>
</head>
<body>
    @using (Ajax.BeginForm(new AjaxOptions(){OnSuccess = "afterEdit"})) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>修改用户信息</legend>
    
            @Html.HiddenFor(model => model.ID)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.UName,"用户名")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.UName)
                @Html.ValidationMessageFor(model => model.UName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Pwd,"密码")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Pwd)
                @Html.ValidationMessageFor(model => model.Pwd)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.ShowName,"显示名")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ShowName)
                @Html.ValidationMessageFor(model => model.ShowName)
            </div>
    
           
                @Html.HiddenFor(model => model.DelFlag)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Remark,"备注")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Remark)
                @Html.ValidationMessageFor(model => model.Remark)
            </div>
    
         
                @Html.HiddenFor(model => model.ModfiedOn)
                @Html.HiddenFor(model => model.SubTime)
            <p>
                <input type="submit" value="保存" />
            </p>
        </fieldset>
    }
    
  
</body>
</html>

Heima8.OA.UI.Portal/Views/UserInfo/Index.cshtml
@model IEnumerable<Heima8.OA.Model.UserInfo>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @*<link href="~/Content/tableStyle.css" rel="stylesheet" />*@
    
    <link href="~/Content/jquery-easyui-1.3.1/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/jquery-easyui-1.3.1/themes/icon.css" rel="stylesheet" />

    <script src="~/Content/jquery-easyui-1.3.1/jquery-1.8.0.min.js"></script>
    <script src="~/Content/jquery-easyui-1.3.1/jquery.easyui.min.js"></script>
    <script src="~/Content/jquery-easyui-1.3.1/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        $(function () {
            initTable();

            $("#addDialogDiv").css("display", "none");
            $("#editDialogDiv").css("display", "none");
            $("#setRoleDialogDiv").css("display", "none");
            $("#setActionDialogDiv").css("display", "none");
            
            bindSearchBtnClick();

        });

        //绑定搜索查询事件
        function bindSearchBtnClick() {
            $("#btnSearch").click(function() {
                var data= {schName:$("#txtSchName").val(),schRemark:$("#txtSchReamrk").val()};
                initTable(data);
            });
        }

        //初始化表格
        function initTable(queryParam) {
            $('#tt').datagrid({
                url: '/UserInfo/GetAllUserInfos',//rows:一页有多少条，page：请求当前页
                title: '用户信息列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'ID',
                loadMsg: '正在加载用户的信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30],
                queryParams: queryParam,//让表格在加载数据的时候，额外传输的数据。
                columns: [[
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '用户的编号', width: 80 },
                    { field: 'UName', title: '用户名', width: 120 },
                    { field: 'Pwd', title: '密码', width: 120 },
                    { field: 'Remark', title: '备注', width: 120 },
                    {
                        field: 'SubTime', title: '提交时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d h:m:s");
                        }
                    },
                    {
                        field: 'ModfiedOn', title: '操作', width: 120, formatter: function (value, row, index) {
                            var str = "";
                            str += "<a href='javascript:void(0)' class='editLink' uid='" + row.ID + "'>修改</a> &nbsp;&nbsp;";
                            str += "<a href='javascript:void(0)' class='deletLink' uid='" + row.ID + "'>删除</a>";
                            return str;
                        }
                    }
                ]],
                toolbar: [{
                    id: 'btnDownShelf',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        //alert("dd");
                        //弹出一个添加的对话框
                        addClickEvent();
                    }
                }, {
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        deleteEvent();
                    }
                }, {
                    id: 'btnEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: function () {
                        //校验你是否只选中一个 用户
                        var selectedRows = $('#tt').datagrid("getSelections");
                        if (selectedRows.length != 1) {
                            //error,question,info,warning.
                            $.messager.alert("错误提醒", "请选中1行要修改数据！", "question");
                            return;
                        }

                        editEvent(selectedRows[0].ID);
                    }
                }, {
                    id: 'btnSetRole',
                    text: '设置角色',
                    iconCls: 'icon-redo',
                    handler: function () {
                        //判断是否选中一个用户进行角色设置。弹出一个设置角色的对话框出来。
                        setRole();
                    }
                } , {
                    id: 'btnSetAction',
                    text: '设置特殊权限',
                    iconCls: 'icon-redo',
                    handler: function () {
                        //判断是否选中一个用户进行角色设置。弹出一个设置角色的对话框出来。
                        setAction();
                    }
                }],
                onHeaderContextMenu: function (e, field) {

                },
                onLoadSuccess: function(data) {
                    $(".editLink").click(function () {//
                        editEvent($(this).attr("uid"));
                        return false;
                    });
                }
            });
        }

        //设置特殊权限
        function setAction() {
            var selectedRows = $('#tt').datagrid("getSelections");
            if (selectedRows.length != 1) {
                //error,question,info,warning.
                $.messager.alert("错误提醒", "请选中一个用户进行设置权限！", "question");
                return;
            }

            $("#setActionFrame").attr("src", "/UserInfo/SetAction/" + selectedRows[0].ID);

            //弹出设置权限的对话框
            $("#setActionDialogDiv").css("display", "block");
            $("#setActionDialogDiv").dialog({
                title: "设置用户特殊权限",
                modal: true,
                width: 600,
                height: 500,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true
            });
        }

        //设置角色成功之后关闭对话框
        function afterSetRole() {
            $("#setRoleDialogDiv").dialog("close");
        }

        // 设置用户角色
        function setRole() {
            var selectedRows = $('#tt').datagrid("getSelections");
            if (selectedRows.length != 1) {
                //error,question,info,warning.
                $.messager.alert("错误提醒", "请选中一个用户进行设置角色！", "question");
                return;
            }

            $("#setRoleFrame").attr("src", "/UserInfo/SetRole/" + selectedRows[0].ID);

            //弹出设置角色对话框
            $("#setRoleDialogDiv").css("display", "block");
            $("#setRoleDialogDiv").dialog({
                title: "设置用户角色",
                modal: true,
                width: 400,
                height: 400,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '设置',
                    iconCls: 'icon-ok',
                    handler: function() {
                        $("#setRoleFrame")[0].contentWindow.submitForm();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $("#setRoleDialogDiv").dialog("close");
                    }
                }]
            });
        }

        //修改
        function editEvent(id) {
           
            //给editFrame  的src属性做一个赋值
            $("#editFrame").attr("src", "/UserInfo/Edit/" +id);

            $("#editDialogDiv").css("display", "block");
            $("#editDialogDiv").dialog({
                title: "修改用户",
                modal: true,
                width: 400,
                height: 400,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '修改',
                    iconCls: 'icon-ok',
                    handler: function() {
                        $("#editFrame")[0].contentWindow.submitForm();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $("#editDialogDiv").dialog("close");
                    }
                }]
            });
        }
        //修改成功之后由子容器来调用的
        function afterEditSuccess() {
            $("#editDialogDiv").dialog("close");
            initTable();
        }

        //删除按钮被点击的时候执行。
        function deleteEvent() {
            //第一步拿到  easyui里面的选中的项
            var selectedRows = $('#tt').datagrid("getSelections");
            if (selectedRows.length <= 0) {
                //error,question,info,warning.
                $.messager.alert("错误提醒", "请选中删除数据！", "question");
                return;
            }

            var ids = "";
            // 把数据删除
            for (var key in selectedRows) {
                ids = ids + selectedRows[key].ID + ",";
            }
            //ids:     1,2,       4,5,6,
            ids = ids.substr(0, ids.length - 1);
            
            $.post("/UserInfo/Delete", { ids: ids }, function(data) {
                if (data == "ok") {
                    //刷新表格
                    initTable();
                } else {
                    $.messager.alert("提醒消息", "败了", "error");
                }
            });

        }

        //当用户点击添加时候，弹出一个添加的对话框
        function addClickEvent() {
            $("#addDialogDiv").css("display", "block");
            $("#addDialogDiv").dialog({
                title: "添加用户",
                modal: true,
                width: 400,
                height: 400,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                        id: 'btnOk',
                        text: '添加',
                        iconCls: 'icon-ok',
                        handler:subAddForm 
                    }, {
                        id: 'btnCancel',
                        text: '取消',
                        iconCls: 'icon-cancel',
                        handler: function () {
                            $("#addDialogDiv").dialog("close");
                        }
                    }]
            });
        }
        
        //把表单提交到后台。
        function subAddForm() {
            $("#addDialogDiv form").submit();
        }

        //添加成功过之后执行的代码
        function afterAdd(data) {
            if (data == "ok") {
                //关闭对话框刷新表格
                $("#addDialogDiv").dialog("close");
                initTable();
            } else {
                $.messager.alert(data);
            }
        }
    </script>
</head>
    <body>
        <div>
            用户名： <input type="text" id="txtSchName" name="txtSchName" /> 备注：<input type="text" name="txtSchReamrk" id="txtSchReamrk"/> <input type="button" id="btnSearch" value="搜索"/>
        </div>
        

        @*当前页面放表格数据的地方*@
        <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit">
        </table>

        <!----------------弹出来的添加的 对话框- 开始------------>
        <div id="addDialogDiv">
            @using (Ajax.BeginForm("Add","UserInfo",new AjaxOptions(){OnSuccess = "afterAdd"}))
            {
                <table class="t3">
                    <tr>
                        <td>用户名：</td><td><input type="text" name="UName"/></td>
                    </tr>   
                    <tr>
                        <td>密码：</td><td><input type="text" name="Pwd"/></td>
                    </tr>     
                    <tr>
                        <td>备注：</td><td><input type="text" name="Remark"/></td>
                    </tr>     
                    <tr>
                        <td>昵称：</td><td><input type="text" name="ShowName"/></td>
                    </tr>     
                </table>
            }
        </div>
        <!----------------弹出来的添加的 对话框- 结束------------>
    

        <!----------------弹出来的修改的 对话框- 开始------------>
        <div id="editDialogDiv">
            <iframe id="editFrame" src="javascript:void(0)" frameborder="0" width="100%" height="100%" scrolling="no"></iframe>
        </div>
        <!----------------弹出来的修改的 对话框- 结束------------>
    
    
        <!----------------弹出来设置角色 对话框- 开始------------>
        <div id="setRoleDialogDiv">
            <iframe id="setRoleFrame" src="javascript:void(0)" frameborder="0" width="100%" height="100%" scrolling="no"></iframe>
        </div>
        <!----------------弹出来设置角色 对话框- 结束------------>
        
           <!----------------弹出来设置特殊权限的 对话框- 开始------------>
        <div id="setActionDialogDiv">
            <iframe id="setActionFrame" src="javascript:void(0)" frameborder="0" width="100%" height="100%" scrolling="no"></iframe>
        </div>
        <!----------------弹出来的修改的 对话框- 结束------------>
    </body>
</html>

Heima8.OA.UI.Portal/Views/UserInfo/SetAction.cshtml
@model IEnumerable<Heima8.OA.Model.ActionInfo>

@using Heima8.OA.Model
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetAction</title>
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script type="text/javascript">
        $(function () {

            $(":radio").click(function() {
                //发送异步请求。
                //拿到用户id  权限的id
                var uId = $(this).attr("uId");
                var actionId = $(this).attr("actionId");
                var value = $(this).val();

                $.post("/UserInfo/SetUserAction",{UId:uId,ActionId:actionId,Value:value});
            });

            $(".btnDel").click(function () {
                if ($(this).siblings(":checked").length > 0) {
                    //后台删除数据。
                    $.post("/UserInfo/DeleteUserAction", { UId: $(this).attr("uId"), ActionId: $(this).attr("actionId") }, function (data) {
                        
                    });
                }

                //前端删除显示状态。
                $(this).siblings(":radio").attr("checked", false);
               
            });
        });
    </script>
</head>
<body>
    <div>
        @{
            UserInfo user = ViewBag.User;
        }
        <h3>给用户： @user.UName   设置特殊权限</h3>
        @{
            <table>
                <tr>
                    <th>权限Id</th>
                    <th>权限名</th>
                    <th>权限地址</th>
                    <th>请求方法</th>
                    <th>操作</th>
                </tr>

                @foreach (var actionInfo in Model)
                {
                    string strId = "rd_" + actionInfo.ID;
                    
                    <tr>
                        <td>@actionInfo.ID</td>
                        <td>@actionInfo.ActionName</td>
                        <td>@actionInfo.Url</td>
                        <td>@actionInfo.HttpMethd</td>
                        <td >
                            允许<input uId="@user.ID" actionId="@actionInfo.ID" type="radio" name="@strId" value="1"/>
                            &nbsp;
                            拒绝<input uId="@user.ID" actionId="@actionInfo.ID" type="radio" name="@strId" value="0"/>
                            <input type="button" uId="@user.ID" actionId="@actionInfo.ID" class="btnDel" value="删除" id="btnDelet"/>
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
</body>
</html>

Heima8.OA.UI.Portal/Views/UserInfo/SetRole.cshtml
@using Heima8.OA.Model
@model Heima8.OA.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function afterSetRole(data) {
            if (data == "ok") {
                window.parent.window.afterSetRole();
            }
        }

        function submitForm() {
            $("form").submit();
        }
    </script>
</head>
<body>
    <div>
        <h2>当前给用户：  @Model.UName 设置角色</h2>
        <hr />
        @{
            //所有的角色
            List<RoleInfo> allRoles = ViewBag.AllRoles;
            //所有当前用户已经存在的角色
            List<int> existRoleIdList = ViewBag.ExitsRoles;
            
            using (Ajax.BeginForm("ProcessSetRole", "UserInfo", new AjaxOptions() { OnSuccess = "afterSetRole" }))
            {

            <input type="hidden" name="UId" value="@Model.ID"/>
                
                int i = 0;
                foreach (var roleInfo in allRoles)
                {
                    string str = "ckb_" + roleInfo.ID;
                    if (i % 3 == 0 && i != 0)
                    {
                        <hr />
                    }
                    if (existRoleIdList.Contains(roleInfo.ID))
                    {
                        <input type="checkbox" checked="checked" value="@str" name="@str" id="@str"/>
                    }
                    else
                    {
                        <input type="checkbox"  value="@str" name="@str" id="@str"/>
                    }
                    
                    <label for="@str">@roleInfo.RoleName</label>

                    i++;

                }
            }
        }
    </div>
</body>
</html>