Heima8.OA.UI.Portal/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Heima8.OA.Common;
using Heima8.OA.IBLL;
using Heima8.OA.UI.Portal.Models;

namespace Heima8.OA.UI.Portal.Controllers
{
    [LoginCheckFilter(IsCheck = false)]
    public class UserLoginController : Controller
    {
        //
        // GET: /UserLogin/
        public IUserInfoService UserInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        #region 验证码

        public ActionResult ShowVCode()
        {
            Common.ValidateCode validateCode = new ValidateCode();
            string strCode = validateCode.CreateValidateCode(4);

            //验证码放到Session
            Session["VCode"] = strCode;

            byte[] imgBytes = validateCode.CreateValidateGraphic(strCode);

            return File(imgBytes, @"image/jpeg");

        } 
        #endregion


        #region 处理登录的表单
        public ActionResult ProcessLogin()
        {
            //第一步：处理验证码。
            //拿到表单中的验证码
            #region 验证码
            string strCode = Request["vCode"];

            //拿到Session中的验证码
            string sessionCode = Session["VCode"] as string;

            Session["VCode"] = null;
            if (string.IsNullOrEmpty(sessionCode))
            {
                return Content("验证码错误");
            }

            if (strCode != sessionCode)
            {
                return Content("验证码错误！");
            } 
            #endregion

            //第二步：处理验证4用户名密码
            string name = Request["LoginCode"];
            string pwd = Request["LoginPwd"];
            short delNormal =(short) Heima8.OA.Model.Enum.DelFlagEnum.Normal;
            var userInfo =
                UserInfoService.GetEntities(u => u.UName == name && u.Pwd == pwd && u.DelFlag == delNormal)
                               .FirstOrDefault();

            if (userInfo == null)//没有查询出数据来。
            {
                return Content("用户名密码错误！会登录吗？");
            }

            //Session["loginUser"] = userInfo;
            //用memcache+cookie代替之。
            //立即分配一个标志，Guid。把标志作为 mm存储数据的key，把用户对象放到 mm。 把guid写到客户端cookie里面去。
            string userLoginId = Guid.NewGuid().ToString();

            //把用户的数据写到mm,怎么解决变化：写到不同地方去，可能同时写入多个地方。
            Common.Cache.CacheHelper.AddCache(userLoginId,userInfo,DateTime.Now.AddMinutes(20));

            //往客户端写入cookie
            Response.Cookies["userLoginId"].Value = userLoginId;

            //如果正确那么跳转到首页。
            return Content("ok");
        }
        #endregion

    }
}

Heima8.OA.UI.Portal/Views/UserLogin/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>   
    <title>XX后台管理系统登录</title>
    <script type="text/javascript">
        if (window.parent.window != window) {
            window.top.location.href = "/UserLogin/Index";
        }
    </script>
    <script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="../../Scripts/jquery.validate.min.js" type="text/javascript"></script>

    <style type="text/css">
        *
        {
            padding: 0;
            margin: 0;
        }
        body
        {
            text-align: center;
            background: #4974A4;
        }
        #login
        {
            width: 740px;
            margin: 0 auto;
            font-size: 12px;
        }
        #loginlogo
        {
            width: 700px;
            height: 100px;
            overflow: hidden;
            background: url('/Content/Images/login/logo.png') no-repeat;
            margin-top: 50px;
        }
        #loginpanel
        {
            width: 729px;
            position: relative;
            height: 300px;
        }
        .panel-h
        {
            width: 729px;
            height: 20px;
            background: url('/Content/Images/login/panel-h.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }
        .panel-f
        {
            width: 729px;
            height: 13px;
            background: url('/Content/Images/login/panel-f.gif') no-repeat;
            position: absolute;
            bottom: 0px;
            left: 0px;
            z-index: 3;
        }
        .panel-c
        {
            z-index: 2;
            background: url('/Content/Images/login/panel-c.gif') repeat-y;
            width: 729px;
            height: 300px;
        }
        .panel-c-l
        {
            position: absolute;
            left: 60px;
            top: 40px;
        }
        .panel-c-r
        {
            position: absolute;
            right: 20px;
            top: 50px;
            width: 222px;
            line-height: 200%;
            text-align: left;
        }
        .panel-c-l h3
        {
            color: #556A85;
            margin-bottom: 10px;
        }
        .panel-c-l td
        {
            padding: 7px;
        }
        .login-text
        {
            height: 24px;
            left: 24px;
            border: 1px solid #e9e9e9;
            background: #f9f9f9;
        }
        .login-text-focus
        {
            border: 1px solid #E6BF73;
        }
        .login-btn
        {
            width: 114px;
            height: 29px;
            color: #E9FFFF;
            line-height: 29px;
            background: url('/Content/Images/login/login-btn.gif') no-repeat;
            border: none;
            overflow: hidden;
            cursor: pointer;
        }
        #txtUsername, #code, #txtPassword
        {
            width: 191px;
        }
        #logincopyright
        {
            text-align: center;
            color: White;
            margin-top: 50px;
        }
        a
        {
            color: Black;
        }
        a:hover
        {
            color: Red;
            text-decoration: underline;
        }
    </style>
    
    <script type="text/javascript">
        $(function() {
            //验证码图片呗点击的时候。改变一下
            $("#imgCode").click(changeCheckCode);
        });

        //改变当前图片的地址
        function changeCheckCode() {
            var old = $("#imgCode").attr("src");
            var now= new Date();
            var str = old +
                now.getDay() +
                now.getSeconds() +
                now.getMinutes();
            
            $("#imgCode").attr("src", str);
        }

        //登录成功之后执行此方法。
        function afterLogin(data) {
            if (data == "ok") {
                //登录成功
                window.location.href = "/Home/Index";
            } else {
                alert(data);
                changeCheckCode();
            }
        }
    </script>
    

</head>
<body style="padding: 10px">
    
    @using(Ajax.BeginForm("ProcessLogin","UserLogin",new AjaxOptions(){OnSuccess = "afterLogin"}))
    {
    <div id="login">
        <div id="loginlogo">
        </div>
        <div id="loginpanel">
            <div class="panel-h">
            </div>
            <div class="panel-c">
                <div class="panel-c-l">
                
                    <table cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td align="left" colspan="2">
                                    <h3>
                                        请使用后台管理系统账号登录</h3>
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    账号：
                                </td>
                                <td align="left">
                                    <input type="text" name="LoginCode" value="admin" id="LoginCode" class="login-text" />
                                   
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    密码：
                                </td>
                                <td align="left">
                                    <input type="password" name="LoginPwd" id="LoginPwd" value="123" class="login-text" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    验证码：
                                </td>
                                <td align="left">
                                    <input type="text" class="login-text" id="code" name="vCode" value="1" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td>
                                    <img id="imgCode" src="/UserLogin/ShowVCode?id=2" style="float: left; height: 24px;" />
                                    <div style="float: left; margin-left: 5px; margin-top: 10px;">
                                        <a href="javascript:void(0)" onclick="changeCheckCode();return false;">看不清，换一张</a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" colspan="2">
                                    <input type="submit" id="btnLogin" value="登录" class="login-btn" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="panel-c-r">
                    <p>
                        请从左侧输入登录账号和密码登录</p>
                    <p>
                        如果遇到系统问题，请联系网络管理员。</p>
                    <p>
                        如果没有账号，请联系网站管理员。
                    </p>
                    <p>
                        ......</p>
                </div>
            </div>
            <div class="panel-f">
            </div>
        </div>
        <div id="logincopyright">
            Copyright ? 2012 itcast.cn
        </div>
    </div>
    }
</body>
</html>