Heima8.OA.UI.Portal/Controllers/RoleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Heima8.OA.IBLL;
using Heima8.OA.Model;

namespace Heima8.OA.UI.Portal.Controllers
{
    public class RoleInfoController : BaseController
    {
        //
        // GET: /RoleInfo/
        short delflagNormal = (short)Heima8.OA.Model.Enum.DelFlagEnum.Normal;
        public IRoleInfoService RoleInfoService { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        #region load roleinfos
        public ActionResult GetAllRoleInfos()
        {
            //easyui: table在初始化时候自动发送以下两个参数值。
            int pageSize = int.Parse(Request["rows"] ?? "10");
            int pageIndex = int.Parse(Request["page"] ?? "1");
            int total = 0;

            var temp = RoleInfoService.GetPageEntities(pageSize, pageIndex, out total,
                                              u => u.DelFlag == delflagNormal, u => u.ID, true);

            var tempData =
                temp.Select(
                    a =>
                    new
                    {
                        a.ID,
                        a.RoleName,
                        a.Remark,
                        a.SubTime,
                        a.ModfiedOn,
                        a.DelFlag

                    });

            var data = new { total = total, rows = tempData.ToList() };
            return Json(data, JsonRequestBehavior.AllowGet);
        } 
        #endregion

        #region Add
        public ActionResult Add(RoleInfo roleInfo)
        {
            roleInfo.DelFlag = delflagNormal;
            roleInfo.ModfiedOn = DateTime.Now;
            roleInfo.SubTime = DateTime.Now;
            RoleInfoService.Add(roleInfo);
            return Content("ok");
        }
        #endregion

    }
}

Heima8.OA.UI.Portal/Views/RoleInfo/Index.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @*<link href="~/Content/tableStyle.css" rel="stylesheet" />*@

    <link href="~/Content/jquery-easyui-1.3.1/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/jquery-easyui-1.3.1/themes/icon.css" rel="stylesheet" />

    <script src="~/Content/jquery-easyui-1.3.1/jquery-1.8.0.min.js"></script>
    <script src="~/Content/jquery-easyui-1.3.1/jquery.easyui.min.js"></script>
    <script src="~/Content/jquery-easyui-1.3.1/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    
    <script src="~/Scripts/MyAjaxForm.js"></script>

    <script type="text/javascript">
        $(function () {
            initTable();

            $("#addDialogDiv").css("display", "none");
            $("#editDialogDiv").css("display", "none");
            $("#trIconUrl").css("display", "none");


            bindSearchBtnClick();

            bindCkbIsMenuClick();

            //绑定  上传图片按钮的点击事件
            bindUploadBtnClick();

        });

        //绑定一个上传图片的按钮点击事件
        function bindUploadBtnClick() {
            $("#btnUploadFile").click(function () {
                $("#addDialogDiv form").ajaxSubmit({
                    url: "/ActionInfo/UploadImage",
                    type: "Post",
                    success: function (data) {
                        //把返回的url地址放到页面的隐藏域
                        $("#MenuIcon").val(data);
                        $("#uploadImg").html("<img src='" + data + "' style='width:100px;height:100px;' />");
                    }
                });
            });
        }

        function bindCkbIsMenuClick() {
            $("#ckbIsMenu").change(function () {
                //显示或者隐藏那个  图标地址
                $("#trIconUrl").toggle();
            });
        }



        //绑定搜索查询事件
        function bindSearchBtnClick() {
            $("#btnSearch").click(function () {
                var data = { schName: $("#txtSchName").val(), schRemark: $("#txtSchReamrk").val() };
                initTable(data);
            });
        }

        //初始化表格
        function initTable(queryParam) {
            $('#tt').datagrid({
                url: '/RoleInfo/GetAllRoleInfos',//rows:一页有多少条，page：请求当前页
                title: '角色信息列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'ID',
                loadMsg: '正在加载角色的信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30],
                queryParams: queryParam,//让表格在加载数据的时候，额外传输的数据。
                columns: [[
                        // a.ID,
                        //a.RoleName,
                        //a.Remark,
                        //a.SubTime,
                        //a.ModfiedOn,
                        //a.DelFlag,
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },
                    { field: 'RoleName', title: '角色名', width: 120 },
                    { field: 'Remark', title: '备注', width: 120 },
                    {
                        field: 'SubTime', title: '提交时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d h:m:s");
                        }
                    },
                    {
                        field: 'ModfiedOn', title: '操作', width: 120, formatter: function (value, row, index) {
                            var str = "";
                            str += "<a href='javascript:void(0)' class='editLink' uid='" + row.ID + "'>修改</a> &nbsp;&nbsp;";
                            str += "<a href='javascript:void(0)' class='deletLink' uid='" + row.ID + "'>删除</a>";
                            return str;
                        }
                    }
                ]],
                toolbar: [{
                    id: 'btnDownShelf',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        //alert("dd");
                        //弹出一个添加的对话框
                        addClickEvent();
                    }
                }, {
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        deleteEvent();
                    }
                }, {
                    id: 'btnEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: function () {
                        //校验你是否只选中一个 角色
                        var selectedRows = $('#tt').datagrid("getSelections");
                        if (selectedRows.length != 1) {
                            //error,question,info,warning.
                            $.messager.alert("错误提醒", "请选中1行要修改数据！", "question");
                            return;
                        }

                        editEvent(selectedRows[0].ID);
                    }
                }],
                onHeaderContextMenu: function (e, field) {

                },
                onLoadSuccess: function (data) {
                    $(".editLink").click(function () {//
                        editEvent($(this).attr("uid"));
                        return false;
                    });
                }
            });
        }

        //修改
        function editEvent(id) {

            //给editFrame  的src属性做一个赋值
            $("#editFrame").attr("src", "/ActionInfo/Edit/" + id);

            $("#editDialogDiv").css("display", "block");
            $("#editDialogDiv").dialog({
                title: "修改角色",
                modal: true,
                width: 400,
                height: 400,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '修改',
                    iconCls: 'icon-ok',
                    handler: function () {
                        $("#editFrame")[0].contentWindow.submitForm();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $("#editDialogDiv").dialog("close");
                    }
                }]
            });
        }
        //修改成功之后由子容器来调用的
        function afterEditSuccess() {
            $("#editDialogDiv").dialog("close");
            initTable();
        }

        //删除按钮被点击的时候执行。
        function deleteEvent() {
            //第一步拿到  easyui里面的选中的项
            var selectedRows = $('#tt').datagrid("getSelections");
            if (selectedRows.length <= 0) {
                //error,question,info,warning.
                $.messager.alert("错误提醒", "请选中删除数据！", "question");
                return;
            }

            var ids = "";
            // 把数据删除
            for (var key in selectedRows) {
                ids = ids + selectedRows[key].ID + ",";
            }
            //ids:     1,2,       4,5,6,
            ids = ids.substr(0, ids.length - 1);

            $.post("/ActionInfo/Delete", { ids: ids }, function (data) {
                if (data == "ok") {
                    //刷新表格
                    initTable();
                } else {
                    $.messager.alert("提醒消息", "败了", "error");
                }
            });

        }

        //当角色点击添加时候，弹出一个添加的对话框
        function addClickEvent() {
            $("#addDialogDiv").css("display", "block");
            $("#addDialogDiv").dialog({
                title: "添加角色",
                modal: true,
                width: 400,
                height: 400,
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '添加',
                    iconCls: 'icon-ok',
                    handler: subAddForm
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        $("#addDialogDiv").dialog("close");
                    }
                }]
            });
        }

        //把表单提交到后台。
        function subAddForm() {
            $("#addDialogDiv form").submit();
        }

        //添加成功过之后执行的代码
        function afterAdd(data) {
            if (data == "ok") {
                //关闭对话框刷新表格
                $("#addDialogDiv").dialog("close");
                initTable();
            } else {
                $.messager.alert(data);
            }
        }
    </script>
</head>
<body>
    <div>
        角色名：
        <input type="text" id="txtSchName" name="txtSchName" />
        备注：<input type="text" name="txtSchReamrk" id="txtSchReamrk" />
        <input type="button" id="btnSearch" value="搜索" />
    </div>


    @*当前页面放表格数据的地方*@
    <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit">
    </table>

    <!----------------弹出来的添加的 对话框- 开始------------>
    <div id="addDialogDiv">
        @using (Ajax.BeginForm("Add", "RoleInfo", new AjaxOptions() { OnSuccess = "afterAdd" }))
        {
                     
            
            <table class="t3">
                <tr>
                    <td>角色名：</td>
                    <td>
                        <input type="text" name="RoleName" /></td>
                </tr>
               
                <tr>
                    <td>备注：</td>
                    <td>
                        <input type="text" name="Remark" /></td>
                </tr>

            </table>
        }
    </div>
    <!----------------弹出来的添加的 对话框- 结束------------>


    <!----------------弹出来的修改的 对话框- 开始------------>
    <div id="editDialogDiv">
        <iframe id="editFrame" src="javascript:void(0)" frameborder="0" width="100%" height="100%" scrolling="no"></iframe>
    </div>
    <!----------------弹出来的修改的 对话框- 结束------------>


</body>
</html>